language: python
python:
  - "3.5"
  - "3.6"
  - "pypy3"
os:
  - linux
env:
  - USIM_WAITQUEUE="" DEBUG="-O"
  - USIM_WAITQUEUE=""
  - USIM_WAITQUEUE="SD"
  - USIM_WAITQUEUE="CY"
before_script:
  - python -m pip install pip --upgrade
  - python -m pip list
  - export PYTHONHASHSEED=${PYTHONHASHSEED:-${RANDOM}}
  - echo "export PYTHONHASHSEED=${PYTHONHASHSEED}"
  - pip install .[contrib]
  - pip install codecov
  - |
    [ "$USIM_WAITQUEUE" == "CY" ] && pip install cython || true
  - export COVERAGE_PROCESS_START=$(pwd)/.coveragerc
  - export PYTEST_ADDOPTS=-v
script:
  - python -m flake8
  - python $DEBUG -m coverage run setup.py test
after_success:
  - coverage report && codecov
