language: python
python:
  - "3.5"
  - "3.6"
  - "pypy3"
os:
  - linux
env:
  - USIM_WAITQUEUE=
  - USIM_WAITQUEUE=SD
  - USIM_WAITQUEUE=CY
before_script:
  - pip install pip --upgrade
  - python3 -m pip list
  - export PYTHONHASHSEED=${PYTHONHASHSEED:-${RANDOM}}
  - echo "export PYTHONHASHSEED=${PYTHONHASHSEED}"
  - pip install .[contrib]
  - pip install codecov
  - |
    [ "$USIM_WAITQUEUE" == "CY" ] && pip install cython || true
  - export COVERAGE_PROCESS_START=$(pwd)/.coveragerc
  - export PYTEST_ADDOPTS=-v
script:
  - |
    [[ "x$USIM_WAITQUEUE" == "x" ]] || python -m flake8 && python -m mypy usim
  - coverage run setup.py test
after_success:
  - coverage report && codecov
